### ISSUE TITLE
Requests failing to be redirected

### ISSUE THREAD

**Issue by qilinmoe** [SpikeHD/reMITM#1]
As stated on the title.

Logs:
```
2023-07-05 21:56:06 | [INFO] == Initializing 2023-07-05 21:56:06 ==
2023-07-05 21:56:06 | [INFO] Redirecting requests to: google.com:443
2023-07-05 21:56:07 | [INFO] Installed certificate into Root CA store
2023-07-05 21:56:07 | [INFO] Redirecting requests to: google.com:443
2023-07-05 21:56:11 | [INFO] Connecting...
2023-07-05 21:56:11 | [INFO] Connected to proxy: http=127.0.0.1:8111;https=127.0.0.1:8111
2023-07-05 21:56:11 | [INFO] Proxy process started on port 8111.
2023-07-05 21:56:13 | [INFO] Comparing hoyoverse.com with www.google.com:443
2023-07-05 21:56:17 | [INFO] Comparing hoyoverse.com with http://hoyoverse.com/
2023-07-05 21:56:17 | [INFO] Found URI to redirect: http://hoyoverse.com/
2023-07-05 21:56:17 | [INFO] Redirecting to google.com:443/...
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidUri(InvalidFormat)', src\proxy.rs:108:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-07-05 21:56:17 | [INFO] Comparing hoyoverse.com with http://hoyoverse.com/
2023-07-05 21:56:17 | [INFO] Found URI to redirect: http://hoyoverse.com/
2023-07-05 21:56:17 | [INFO] Redirecting to google.com:443/...
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidUri(InvalidFormat)', src\proxy.rs:108:38
2023-07-05 21:56:17 | [INFO] Comparing hoyoverse.com with http://hoyoverse.com/
2023-07-05 21:56:17 | [INFO] Found URI to redirect: http://hoyoverse.com/
2023-07-05 21:56:17 | [INFO] Redirecting to google.com:443/...
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidUri(InvalidFormat)', src\proxy.rs:108:38
2023-07-05 21:56:17 | [INFO] Comparing hoyoverse.com with http://hoyoverse.com/
2023-07-05 21:56:17 | [INFO] Found URI to redirect: http://hoyoverse.com/
2023-07-05 21:56:17 | [INFO] Redirecting to google.com:443/...
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidUri(InvalidFormat)', src\proxy.rs:108:38
2023-07-05 21:56:17 | [INFO] Comparing hoyoverse.com with http://hoyoverse.com/
2023-07-05 21:56:17 | [INFO] Found URI to redirect: http://hoyoverse.com/
2023-07-05 21:56:17 | [INFO] Redirecting to google.com:443/...
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidUri(InvalidFormat)', src\proxy.rs:108:38
2023-07-05 21:56:17 | [INFO] Comparing hoyoverse.com with http://hoyoverse.com/
2023-07-05 21:56:17 | [INFO] Found URI to redirect: http://hoyoverse.com/
2023-07-05 21:56:17 | [INFO] Redirecting to google.com:443/...
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidUri(InvalidFormat)', src\proxy.rs:108:38
2023-07-05 21:56:17 | [INFO] Comparing hoyoverse.com with http://hoyoverse.com/
2023-07-05 21:56:17 | [INFO] Found URI to redirect: http://hoyoverse.com/
2023-07-05 21:56:17 | [INFO] Redirecting to google.com:443/...
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidUri(InvalidFormat)', src\proxy.rs:108:38
2023-07-05 21:56:17 | [INFO] Comparing hoyoverse.com with http://hoyoverse.com/
2023-07-05 21:56:17 | [INFO] Found URI to redirect: http://hoyoverse.com/
2023-07-05 21:56:17 | [INFO] Redirecting to google.com:443/...
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidUri(InvalidFormat)', src\proxy.rs:108:38
2023-07-05 21:56:17 | [INFO] Comparing hoyoverse.com with http://hoyoverse.com/
2023-07-05 21:56:17 | [INFO] Found URI to redirect: http://hoyoverse.com/
2023-07-05 21:56:17 | [INFO] Redirecting to google.com:443/...
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidUri(InvalidFormat)', src\proxy.rs:108:38
2023-07-05 21:56:17 | [INFO] Comparing hoyoverse.com with http://hoyoverse.com/
2023-07-05 21:56:17 | [INFO] Found URI to redirect: http://hoyoverse.com/
2023-07-05 21:56:17 | [INFO] Redirecting to google.com:443/...
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidUri(InvalidFormat)', src\proxy.rs:108:38
```

**Comment by SpikeHD** [comment]
Fixed as of 53bd054
